// Sprite URLs from PokeAPI's sprite collection
export const POKEMON_SPRITES = {
    // Starters and Evolutions
    BULBASAUR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
    IVYSAUR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png',
    VENUSAUR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',
    CHARMANDER: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
    CHARMELEON: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
    CHARIZARD: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
    SQUIRTLE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
    WARTORTLE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png',
    BLASTOISE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',

    // Early Route Pokemon
    CATERPIE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
    METAPOD: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png',
    BUTTERFREE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png',
    WEEDLE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',
    KAKUNA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png',
    BEEDRILL: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png',
    PIDGEY: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
    PIDGEOTTO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png',
    PIDGEOT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png',
    RATTATA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',
    RATICATE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png',
    SPEAROW: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png',
    FEAROW: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png',
    EKANS: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png',
    ARBOK: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png',

    // Pikachu Family
    PIKACHU: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
    RAICHU: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png',

    // Sandshrew to Nidoking
    SANDSHREW: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png',
    SANDSLASH: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png',
    NIDORAN_F: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png',
    NIDORINA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png',
    NIDOQUEEN: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png',
    NIDORAN_M: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png',
    NIDORINO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png',
    NIDOKING: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png',

    // Fairy Types and Moon Stone Evolutions
    CLEFAIRY: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png',
    CLEFABLE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png',
    VULPIX: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png',
    NINETALES: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png',
    JIGGLYPUFF: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',
    WIGGLYTUFF: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png',

    // Cave Pokemon
    ZUBAT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png',
    GOLBAT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png',
    ODDISH: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',
    GLOOM: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png',
    VILEPLUME: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png',
    PARAS: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png',
    PARASECT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png',
    VENONAT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png',
    VENOMOTH: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png',
    DIGLETT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png',

    // 51-100
    DUGTRIO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png',
    MEOWTH: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
    PERSIAN: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png',
    PSYDUCK: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png',
    GOLDUCK: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png',
    MANKEY: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png',
    PRIMEAPE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png',
    GROWLITHE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
    ARCANINE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png',
    POLIWAG: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png',
    POLIWHIRL: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png',
    POLIWRATH: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png',
    ABRA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png',
    KADABRA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png',
    ALAKAZAM: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png',
    MACHOP: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png',
    MACHOKE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png',
    MACHAMP: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png',
    BELLSPROUT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png',
    WEEPINBELL: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png',
    VICTREEBEL: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png',
    TENTACOOL: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png',
    TENTACRUEL: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png',
    GEODUDE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png',
    GRAVELER: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png',
    GOLEM: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png',
    PONYTA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png',
    RAPIDASH: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png',
    SLOWPOKE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png',
    SLOWBRO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png',
    MAGNEMITE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png',
    MAGNETON: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png',
    FARFETCHD: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png',
    DODUO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png',
    DODRIO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png',
    SEEL: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png',
    DEWGONG: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png',
    GRIMER: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png',
    MUK: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png',
    SHELLDER: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png',
    CLOYSTER: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png',
    GASTLY: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png',
    HAUNTER: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png',
    GENGAR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png',
    ONIX: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png',
    DROWZEE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png',
    HYPNO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png',
    KRABBY: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png',
    KINGLER: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png',
    VOLTORB: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png',

    // 101-151
    ELECTRODE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png',
    EXEGGCUTE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png',
    EXEGGUTOR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png',
    CUBONE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png',
    MAROWAK: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png',
    HITMONLEE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png',
    HITMONCHAN: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png',
    LICKITUNG: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png',
    KOFFING: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png',
    WEEZING: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png',
    RHYHORN: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png',
    RHYDON: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png',
    CHANSEY: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png',
    TANGELA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png',
    KANGASKHAN: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png',
    HORSEA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png',
    SEADRA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png',
    GOLDEEN: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png',
    SEAKING: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png',
    STARYU: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png',
    STARMIE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png',
    MR_MIME: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png',
    SCYTHER: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png',
    JYNX: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png',
    ELECTABUZZ: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png',
    MAGMAR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png',
    PINSIR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png',
    TAUROS: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png',
    MAGIKARP: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png',
    GYARADOS: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png',
    LAPRAS: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png',
    DITTO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png',
    EEVEE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
    VAPOREON: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png',
    JOLTEON: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png',
    FLAREON: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png',
    PORYGON: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png',
    OMANYTE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png',
    OMASTAR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png',
    KABUTO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png',
    KABUTOPS: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png',
    AERODACTYL: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png',
    SNORLAX: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png',
    ARTICUNO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png',
    ZAPDOS: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png',
    MOLTRES: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png',
    DRATINI: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png',
    DRAGONAIR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png',
    DRAGONITE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png',
    MEWTWO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png',
    MEW: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png'
};

// Back sprite URLs for battle scenes
export const POKEMON_BACK_SPRITES = {
    // Starters and Evolutions
    BULBASAUR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/1.png',
    IVYSAUR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/2.png',
    VENUSAUR: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/3.png',
    CHARMANDER: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/4.png',
    CHARMELEON: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/5.png',
    CHARIZARD: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/6.png',
    SQUIRTLE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/7.png',
    WARTORTLE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/8.png',
    BLASTOISE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/9.png',

    // Early Route Pokemon
    CATERPIE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/10.png',
    METAPOD: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/11.png',
    BUTTERFREE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/12.png',
    WEEDLE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/13.png',
    KAKUNA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/14.png',
    BEEDRILL: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/15.png',
    PIDGEY: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/16.png',
    PIDGEOTTO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/17.png',
    PIDGEOT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/18.png',
    RATTATA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/19.png',
    RATICATE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/20.png',
    SPEAROW: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/21.png',
    FEAROW: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/22.png',
    EKANS: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/23.png',
    ARBOK: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/24.png',
    PIKACHU: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png',
    RAICHU: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/26.png',
    SANDSHREW: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/27.png',
    SANDSLASH: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/28.png',
    NIDORAN_F: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/29.png',
    NIDORINA: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/30.png',
    NIDOQUEEN: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/31.png',
    NIDORAN_M: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/32.png',
    NIDORINO: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/33.png',
    NIDOKING: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/34.png',
    CLEFAIRY: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/35.png',
    CLEFABLE: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/36.png',
    VULPIX: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/37.png',
    NINETALES: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/38.png',
    JIGGLYPUFF: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/39.png',
    WIGGLYTUFF: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/40.png',
    ZUBAT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/41.png',
    GOLBAT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/42.png',
    ODDISH: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/43.png',
    GLOOM: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/44.png',
    VILEPLUME: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/45.png',
    PARAS: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/46.png',
    PARASECT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/47.png',
    VENONAT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/48.png',
    VENOMOTH: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/49.png',
    DIGLETT: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/50.png'
}; 